### ISSUE TITLE
Questions on visualization for VRD dataset

### ISSUE THREAD

**Issue by handsomefengfeng** [StanfordVL/ReferringRelationships#13]
I was trying to visualize the trained result on VRD.
Having installed required packages and converting the visualization.ipynb into visualization.py, I ran the command `python visualization.py` but obtained result without attention-heatmap.

Besides, the "Final Heatmaps" I obtained just look like mosaic.

When it comes to "Final Bounding Boxes", error occured. And the log followed.
`Using TensorFlow backend.
person | sky | building | truck | bus | table | shirt | chair | car | train | glasses | tree | boat | hat | trees | grass | pants | road | motorcycle | jacket | monitor | wheel | umbrella | plate | bike | clock | bag | shoe | laptop | desk | cabinet | counter | bench | shoes | tower | bottle | helmet | stove | lamp | coat | bed | dog | mountain | horse | plane | roof | skateboard | traffic light | bush | phone | airplane | sofa | cup | sink | shelf | box | van | hand | shorts | post | jeans | cat | sunglasses | bowl | computer | pillow | pizza | basket | elephant | kite | sand | keyboard | plant | can | vase | refrigerator | cart | skis | pot | surfboard | paper | mouse | trash can | cone | camera | ball | bear | giraffe | tie | luggage | faucet | hydrant | snowboard | oven | engine | watch | face | street | ramp | suitcase

on | wear | has | next to | sleep next to | sit next to | stand next to | park next | walk next to | above | behind | stand behind | sit behind | park behind | in the front of | under | stand under | sit under | near | walk to | walk | walk past | in | below | beside | walk beside | over | hold | by | beneath | with | on the top of | on the left of | on the right of | sit on | ride | carry | look | stand on | use | at | attach to | cover | touch | watch | against | inside | adjacent to | across | contain | drive | drive on | taller than | eat | park on | lying on | pull | talk | lean on | fly | face | play with | sleep on | outside of | rest on | follow | hit | feed | kick | skate on
2019-07-21 18:58:26.328674: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-21 18:58:26.529961: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.92GiB freeMemory: 234.50MiB
2019-07-21 18:58:26.718689: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
totalMemory: 10.92GiB freeMemory: 396.50MiB
2019-07-21 18:58:26.911887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 2 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:82:00.0
totalMemory: 10.92GiB freeMemory: 396.50MiB
2019-07-21 18:58:27.110755: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 3 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:83:00.0
totalMemory: 10.92GiB freeMemory: 396.50MiB
2019-07-21 18:58:27.111219: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1227] Device peer to peer matrix
2019-07-21 18:58:27.111384: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1233] DMA: 0 1 2 3 
2019-07-21 18:58:27.111410: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 0:   Y Y N N 
2019-07-21 18:58:27.111420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 1:   Y Y N N 
2019-07-21 18:58:27.111429: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 2:   N N Y Y 
2019-07-21 18:58:27.111437: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1243] 3:   N N Y Y 
2019-07-21 18:58:27.111454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0, 1, 2, 3
2019-07-21 18:58:28.672098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 180 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-07-21 18:58:28.673583: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 180.50M (189267968 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
2019-07-21 18:58:28.677950: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 117 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1)
2019-07-21 18:58:28.681510: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 117 MB memory) -> physical GPU (device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:82:00.0, compute capability: 6.1)
2019-07-21 18:58:28.685174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 117 MB memory) -> physical GPU (device: 3, name: GeForce GTX 1080 Ti, pci bus id: 0000:83:00.0, compute capability: 6.1)
Found 4 subject attentions
Found 4 object attentions
Found 3 shift attentions
Found 3 inv shift attentions
17
2019-07-21 18:59:22.033085: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 134.20MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-07-21 18:59:22.033246: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 55.69MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-07-21 18:59:22.036407: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 137.62MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2019-07-21 18:59:22.040735: W tensorflow/core/common_runtime/bfc_allocator.cc:219] Allocator (GPU_0_bfc) ran out of memory trying to allocate 146.81MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
Traceback (most recent call last):
  File "visualization.py", line 218, in <module>
    np.maximum(final_object_heatmap[0],0), 14, threshold=0.8)
  File "/home/yyf/ReferringRelationships/utils/visualization_utils.py", line 100, in add_bboxes
    threshold=threshold)
  File "/home/yyf/ReferringRelationships/utils/visualization_utils.py", line 51, in get_bbox_from_heatmap
    ymin = np.min(rows)
  File "/home/yyf/ReferringRelationships/env/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2372, in amin
    out=out, **kwargs)
  File "/home/yyf/ReferringRelationships/env/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
`

Could you please give me some suggestions on these problems?~

Thanks in advance~!

**Comment by handsomefengfeng** [comment]
More detail, I've send an e-mail to you.
Would you please check it out ? ~
Thanks!!!!

**Comment by ranjaykrishna** [comment]
Looks like your local machine ran out of memory. That's the problem.

**Comment by handsomefengfeng** [comment]
Another question is that whether the threshold in visualization.py is needed to be optimized ?

I obtained an unsatisfied result that nothing could be inferred from the heatmap.

I printed the heatmap array to find that most of element in the array are too small for the threshold=0.9 .
