### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by handsomefengfeng** [StanfordVL/ReferringRelationships#9]
I read the  'requirements.txt' the ensured that mine was equipped equally as it.
When I started to train on VRD, I met the problem. 
The log follows:
`Traceback (most recent call last):
  File "train.py", line 70, in <module>
    model = relationships_model.build_model()
  File "/home/yyf/ReferringRelationships/models.py", line 75, in build_model
    return self.build_ssas()
  File "/home/yyf/ReferringRelationships/models.py", line 154, in build_ssas
    subject_att = Concatenate(axis=3)(subject_outputs)
  File "/home/yyf/ReferringRelationships/env/lib/python3.6/site-packages/keras/engine/topology.py", line 583, in __call__
    previous_mask = _collect_previous_mask(inputs)
  File "/home/yyf/ReferringRelationships/env/lib/python3.6/site-packages/keras/engine/topology.py", line 2752, in _collect_previous_mask
    mask = node.output_masks[tensor_index]
IndexError: list index out of range
`

**Comment by ranjaykrishna** [comment]
Strange. It looks like your subject_outputs might be an empty list. Check to see what it contains.

**Comment by CS4Liu** [comment]
I get the same error with you, how do you solve this problem?
Waiting for your advice.
Thakns!
